apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-deployment
  labels:
    app: inventory
spec:
  replicas: 1
  selector:
    # Match all Pods with label "inventory" to the inventory-deployment
    matchLabels:
      app: inventory
  # template is the configurations of the Pod 
  template:
    metadata:
      labels:
        app: inventory
    spec:
      # Container configurations within the pod 
      containers: 
      - name: inventory
        image: us-west2-docker.pkg.dev/csc258-ecommerce-microservices/final-project-repo/inventory:latest
        ports:
        - containerPort: 8000 # Port where the container will listen to
        env:
        - name: redis-host # Name of the environment variable
          valueFrom:
            ConfigMapKeyRef:
              name: redis-config # Name of where we reference from 
              key: redis-host # The value
        - name: redis-port # Name of the environment variable
          valueFrom:
            ConfigMapKeyRef:
              name: redis-config # Name of where we reference from
              key: redis-port # The value
        - name: redis-password # Name of the environment variable
          valueFrom:
            secretKeyRef:
              name: redis-secret # Name of where we reference from
              key: redis-password # The value


